Repository dcanadillas-kube/environment-dcanadillas-cjxd-dev, pull requests merged in 2019-10, with the labels that each got.

#1 chore(config): update configuration
  env/parameters.yaml
  jenkins-x.yml
  jx-requirements.yml
Labels: jx/boot, size/L

#13 Add jx-app-ui 0.0.57
  env/jx-app-ui/README.MD
  env/jx-app-ui/templates/app.yaml
  env/jx-app-ui/values.yaml
  env/requirements.yaml
Labels: size/M

#14 Delete jx-app-ui
  env/requirements.yaml
Labels: size/XS

#15 Add jxui 0.0.886
  env/jxui/README.MD
  env/jxui/templates/app.yaml
  env/requirements.yaml
Labels: size/M

#16 Delete jxui
  env/requirements.yaml
Labels: size/XS

#17 Add jx-app-ui 0.0.57
  env/requirements.yaml
Labels: size/XS

#18 Upgrade all apps
  env/README.MD
  env/requirements.yaml
  env/templates/app.yaml
  env/values.yaml
Labels: size/S

#19 Upgrade jx-app-ui to 0.0.63
  env/jx-app-ui/README.MD
  env/jx-app-ui/templates/app.yaml
  env/requirements.yaml
Labels: size/XS

#20 Delete jx-app-ui
  env/requirements.yaml
Labels: size/XS

#22 Delete jx-app-ui
  env/requirements.yaml
Labels: size/XS

#23 Add jx-app-ui 0.0.68
  env/jx-app-ui/README.MD
  env/jx-app-ui/templates/app.yaml
  env/requirements.yaml
Labels: size/XS
