Repository dcanadillas-kube/environment-dcanadillas-cjxd-dev, pull requests merged in 2020-02, with the labels that each got.

#27 feat(config): upgrade configuration
  OWNERS
  README.md
  bdd/bdd.sh
  bdd/boot-local/jx-requirements.yml
  bdd/boot-vault/README.md
  bdd/boot-vault/cluster.yaml
  bdd/boot-vault/jx-requirements.yml
  env/jenkins-x-platform/values.tmpl.yaml
  env/jxboot-resources/values.tmpl.yaml
  env/values.tmpl.yaml
  jenkins-x.yml
  jx-requirements.yml
  kubeProviders/eks/templates/irsa.tmpl.yaml
  kubeProviders/eks/templates/jenkinsx-policies.yml
  kubeProviders/eks/templates/vault_cf_tmpl.yml
  kubeProviders/eks/values.tmpl.yaml
  systems/acme/Chart.yaml
  systems/acme/templates/cert-manager-prod-certificate.yaml
  systems/acme/templates/cert-manager-prod-issuer.yaml
  systems/acme/templates/cert-manager-staging-certificate.yaml
  systems/acme/templates/cert-manager-staging-issuer.yaml
  systems/acme/values.tmpl.yaml
  systems/cm/values.tmpl.yaml
  systems/external-dns/values.tmpl.yaml
  systems/jx-auth/Chart.yaml
  systems/jx-auth/jx-auth-configmap.tmpl.yaml
  systems/jx-auth/templates/jx-auth-configmap.yaml
  systems/jxing/values.tmpl.yaml
Labels: size/L

#28 Upgrade jx-app-ui to 0.1.36
  env/jx-app-ui/README.MD
  env/jx-app-ui/templates/app.yaml
  env/requirements.yaml
Labels: size/XS

#29 chore(deps): bump https://github.com/dcanadillas/node-jx-test.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/dcanadillas-node-jx-test-sr.yaml
Labels: size/S, updatebot

#30 chore(deps): bump https://github.com/jx-dcanadillas/petclinic-jenkins-x.git
  dependency-matrix/matrix.md
  dependency-matrix/matrix.yaml
  repositories/templates/jx-dcanadillas-petclinic-jenkins-x-sr.yaml
Labels: size/S, updatebot
